### ISSUE TITLE
backward

### ISSUE THREAD

**Issue by michaelklachko** [aliutkus/torchpercentile#1]
Hi, can you please explain the backward function?

**Comment by aliutkus** [comment]
sorry for the delay, currently on vacations. backward on this one is basically a lookup table

**Comment by michaelklachko** [comment]
I meant why do you need a backward pass for it? Do you have an example where you use it in a model?

**Comment by aliutkus** [comment]
sure:

https://github.com/aliutkus/swf

**Comment by michaelklachko** [comment]
I see. What's different compared to torch.kthvalue?

**Comment by aliutkus** [comment]
Sorry I meant:
https://github.com/aliutkus/qsketch

The main difference is: it allows to compute several percentiles at once
